tap "homebrew/bundle"
tap "homebrew/cask-versions"
cask "betterdisplay"
cask "copilot"
cask "firefox-nightly"
cask "iina"
cask "mullvadvpn"
cask "onyx"
cask "orion"
cask "raycast"
cask "readdle-spark"
cask "stats"
cask "telegram"
cask "wezterm"
cask "zoom"

cask "google-chrome"
