require('plugins')
require('treesitter')
require('completion')
require('tree')
require('fuzzy')
require('git')
require('theme')
require('evil_lualine')

require('settings')
require('keymaps')

require('python')
require('lsp')
require('lsp.saga')
require('lsp.lua-ls')
require('lsp.python-ls')
