require('plugins')
require('treesitter')
require('completion')
require('utils')
require('tree')
require('fuzzy')
require('trbl')
require('theme')
require('evil_lualine')
require('git')

require('settings')
require('keymaps')

require('lsp.lua-ls')
require('lsp.python-ls')
require('lsp.go-ls')
